{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "yuyu.fullname" . }}
  labels:
    {{- include "yuyu.labels" . | nindent 4 }}
  {{- $annotations := deepCopy .Values.ingress.annotations }}
  {{- if .Values.ingress.allowedSourceRanges }}
  {{- $key := "traefik.ingress.kubernetes.io/router.middlewares" }}
  {{- $middleware := printf "%s-%s-sources@kubernetescrd" .Release.Namespace (include "yuyu.fullname" .) }}
  {{- if get $annotations $key }}
  {{- $middleware = printf "%s,%s" $middleware (get $annotations $key) }}
  {{- end }}
  {{- $_ := set $annotations $key $middleware }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "yuyu.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
