{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "yuyu.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "yuyu.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressPodLabels | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- include "yuyu.selectorLabels" . | nindent 14 }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: outbox
      ports:
        - protocol: TCP
          port: 3000
{{- end }}
